/* Generated by JASS Version 0.1 64-bit DEBUGGING-build Copyright (c) 2016-2019 Andrew Trotman, University of Otago */
#include <vector>
std::vector<const char*> primary_key =
{
"-",
"1",
"2",
"3",
"4",
"5",
"6",
"7",
"8",
"9",
"10",
};
