/* Generated by JASS Version 0.1 64-bit DEBUGGING-build Copyright (c) 2016-2019 Andrew Trotman, University of Otago */
#include <stddef.h>
#include <stdint.h>
#include"query_heap.h"

using namespace JASS;
void T_6(query_heap &q)
{
	__asm__ (
	"movl	$877, %%edx \n\t"
	"movl	$6, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
void T_1(query_heap &q)
{
	__asm__ (
	"movl	$1024, %%edx \n\t"
	"movl	$1, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
void T_4(query_heap &q)
{
	__asm__ (
	"movl	$930, %%edx \n\t"
	"movl	$4, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
void T_5(query_heap &q)
{
	__asm__ (
	"movl	$902, %%edx \n\t"
	"movl	$5, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
void T_3(query_heap &q)
{
	__asm__ (
	"movl	$959, %%edx \n\t"
	"movl	$3, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
void T_8(query_heap &q)
{
	__asm__ (
	"movl	$829, %%edx \n\t"
	"movl	$8, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
void T_7(query_heap &q)
{
	__asm__ (
	"movl	$852, %%edx \n\t"
	"movl	$7, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
void T_2(query_heap &q)
{
	__asm__ (
	"movl	$990, %%edx \n\t"
	"movl	$2, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
void T_9(query_heap &q)
{
	__asm__ (
	"movl	$807, %%edx \n\t"
	"movl	$9, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
void T_10(query_heap &q)
{
	__asm__ (
	"movl	$786, %%edx \n\t"
	"movl	$10, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
void T_four(query_heap &q)
{
	__asm__ (
	"pushq	%%rbp \n\t"
	"movq	%%rdi, %%rbp \n\t"
	"movl	$339, %%edx \n\t"
	"movl	$7, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$330, %%edx \n\t"
	"movl	$8, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$321, %%edx \n\t"
	"movl	$9, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"popq	%%rbp \n\t"
	"movl	$313, %%edx \n\t"
	"movl	$10, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
void T_eight(query_heap &q)
{
	__asm__ (
	"pushq	%%rbp \n\t"
	"movq	%%rdi, %%rbp \n\t"
	"movl	$93, %%edx \n\t"
	"movl	$3, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$91, %%edx \n\t"
	"movl	$4, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$88, %%edx \n\t"
	"movl	$5, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$85, %%edx \n\t"
	"movl	$6, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$83, %%edx \n\t"
	"movl	$7, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$81, %%edx \n\t"
	"movl	$8, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$79, %%edx \n\t"
	"movl	$9, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"popq	%%rbp \n\t"
	"movl	$77, %%edx \n\t"
	"movl	$10, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
void T_five(query_heap &q)
{
	__asm__ (
	"pushq	%%rbp \n\t"
	"movq	%%rdi, %%rbp \n\t"
	"movl	$264, %%edx \n\t"
	"movl	$6, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$257, %%edx \n\t"
	"movl	$7, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$250, %%edx \n\t"
	"movl	$8, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$243, %%edx \n\t"
	"movl	$9, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"popq	%%rbp \n\t"
	"movl	$237, %%edx \n\t"
	"movl	$10, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
void T_seven(query_heap &q)
{
	__asm__ (
	"pushq	%%rbp \n\t"
	"movq	%%rdi, %%rbp \n\t"
	"movl	$144, %%edx \n\t"
	"movl	$4, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$140, %%edx \n\t"
	"movl	$5, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$136, %%edx \n\t"
	"movl	$6, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$132, %%edx \n\t"
	"movl	$7, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$129, %%edx \n\t"
	"movl	$8, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$125, %%edx \n\t"
	"movl	$9, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"popq	%%rbp \n\t"
	"movl	$122, %%edx \n\t"
	"movl	$10, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
void T_two(query_heap &q)
{
	__asm__ (
	"pushq	%%rbp \n\t"
	"movq	%%rdi, %%rbp \n\t"
	"movl	$564, %%edx \n\t"
	"movl	$9, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"popq	%%rbp \n\t"
	"movl	$550, %%edx \n\t"
	"movl	$10, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
void T_six(query_heap &q)
{
	__asm__ (
	"pushq	%%rbp \n\t"
	"movq	%%rdi, %%rbp \n\t"
	"movl	$201, %%edx \n\t"
	"movl	$5, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$195, %%edx \n\t"
	"movl	$6, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$189, %%edx \n\t"
	"movl	$7, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$184, %%edx \n\t"
	"movl	$8, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$179, %%edx \n\t"
	"movl	$9, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"popq	%%rbp \n\t"
	"movl	$175, %%edx \n\t"
	"movl	$10, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
void T_three(query_heap &q)
{
	__asm__ (
	"pushq	%%rbp \n\t"
	"movq	%%rdi, %%rbp \n\t"
	"movl	$434, %%edx \n\t"
	"movl	$8, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$422, %%edx \n\t"
	"movl	$9, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"popq	%%rbp \n\t"
	"movl	$411, %%edx \n\t"
	"movl	$10, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
void T_one(query_heap &q)
{
	__asm__ (
	"movl	$786, %%edx \n\t"
	"movl	$10, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
void T_nine(query_heap &q)
{
	__asm__ (
	"pushq	%%rbp \n\t"
	"movq	%%rdi, %%rbp \n\t"
	"movl	$46, %%edx \n\t"
	"movl	$2, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$44, %%edx \n\t"
	"movl	$3, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$43, %%edx \n\t"
	"movl	$4, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$42, %%edx \n\t"
	"movl	$5, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$41, %%edx \n\t"
	"movl	$6, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$39, %%edx \n\t"
	"movl	$7, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$38, %%edx \n\t"
	"movl	$8, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$37, %%edx \n\t"
	"movl	$9, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"popq	%%rbp \n\t"
	"movl	$36, %%edx \n\t"
	"movl	$10, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
void T_ten(query_heap &q)
{
	__asm__ (
	"pushq	%%rbp \n\t"
	"movq	%%rdi, %%rbp \n\t"
	"movl	$1, %%edx \n\t"
	"movl	$1, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$1, %%edx \n\t"
	"movl	$2, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$1, %%edx \n\t"
	"movl	$3, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$1, %%edx \n\t"
	"movl	$4, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$1, %%edx \n\t"
	"movl	$5, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$1, %%edx \n\t"
	"movl	$6, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$1, %%edx \n\t"
	"movl	$7, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$1, %%edx \n\t"
	"movl	$8, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"movl	$1, %%edx \n\t"
	"movl	$9, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT \n\t"
	"movq	%%rbp, %%rdi \n\t"
	"popq	%%rbp \n\t"
	"movl	$1, %%edx \n\t"
	"movl	$10, %%esi \n\t"
	"call	_ZN4JASS10query_heap7add_rsvEjt@PLT"
	: : : "edx", "esi", "rdi");
}
